//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.26 at 12:39:30 PM MSK 
//


package by.training.xml_xsd_web_parsing.posts;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Post complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Post">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="image-theme" type="{http://www.epam.training.by/posts}ImageTheme"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="valuable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address-to" type="{http://www.epam.training.by/posts}Address"/>
 *         &lt;element name="recipient" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="artists" type="{http://www.epam.training.by/posts}ArtistList"/>
 *         &lt;element name="type" type="{http://www.epam.training.by/posts}Type"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="year" type="{http://www.w3.org/2001/XMLSchema}gYear" />
 *       &lt;attribute name="is-sent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Post", propOrder = {
        "imageTheme",
        "country",
        "valuable",
        "addressTo",
        "recipient",
        "artists",
        "type"
})
public class Post {

    @XmlElement(name = "image-theme", required = true)
    @XmlSchemaType(name = "string")
    protected ImageTheme imageTheme;
    @XmlElement(required = true)
    protected String country;
    @XmlElement(required = true)
    protected String valuable;
    @XmlElement(name = "address-to", required = true)
    protected Address addressTo;
    @XmlElement(required = true)
    protected String recipient;
    @XmlElement(required = true)
    protected ArtistList artists;
    @XmlElement(required = true)
    protected Type type;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "year")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar year;
    @XmlAttribute(name = "is-sent")
    protected Boolean isSent;

    /**
     * Gets the value of the imageTheme property.
     *
     * @return possible object is
     * {@link ImageTheme }
     */
    public ImageTheme getImageTheme() {
        return imageTheme;
    }

    /**
     * Sets the value of the imageTheme property.
     *
     * @param value allowed object is
     *              {@link ImageTheme }
     */
    public void setImageTheme(ImageTheme value) {
        this.imageTheme = value;
    }

    /**
     * Gets the value of the country property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the valuable property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getValuable() {
        return valuable;
    }

    /**
     * Sets the value of the valuable property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValuable(String value) {
        this.valuable = value;
    }

    /**
     * Gets the value of the addressTo property.
     *
     * @return possible object is
     * {@link Address }
     */
    public Address getAddressTo() {
        return addressTo;
    }

    /**
     * Sets the value of the addressTo property.
     *
     * @param value allowed object is
     *              {@link Address }
     */
    public void setAddressTo(Address value) {
        this.addressTo = value;
    }

    /**
     * Gets the value of the recipient property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRecipient(String value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the artists property.
     *
     * @return possible object is
     * {@link ArtistList }
     */
    public ArtistList getArtists() {
        return artists;
    }

    /**
     * Sets the value of the artists property.
     *
     * @param value allowed object is
     *              {@link ArtistList }
     */
    public void setArtists(ArtistList value) {
        this.artists = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link Type }
     */
    public Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link Type }
     */
    public void setType(Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the year property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setYear(XMLGregorianCalendar value) {
        this.year = value;
    }

    /**
     * Gets the value of the isSent property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isIsSent() {
        if (isSent == null) {
            return true;
        } else {
            return isSent;
        }
    }

    /**
     * Sets the value of the isSent property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsSent(Boolean value) {
        this.isSent = value;
    }

    @Override
    public String toString() {
        return "Post{" +
                "imageTheme=" + imageTheme +
                ", country='" + country + '\'' +
                ", valuable='" + valuable + '\'' +
                ", addressTo=" + addressTo +
                ", recipient='" + recipient + '\'' +
                ", artists=" + artists +
                ", type=" + type +
                ", id='" + id + '\'' +
                ", year=" + year +
                ", isSent=" + isSent +
                '}' + "\n";
    }
}
